spring.application.name=ebank-bot

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.5-flash-lite

spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false

server.port=8058

spring.ai.mcp.client.streamable-http.connections.customer.url=http://localhost:8056/mcp
spring.ai.mcp.client.streamable-http.connections.ebank.url=http://localhost:8057/mcp

discord.token=${DISCORD_TOKEN}
discord.gateway-intents=MESSAGE_CONTENT

telegram.token=${TELEGRAM_TOKEN}
eureka.client.jersey.enabled=false
telegram.username=EbankBotarm